explicit error when the en_US.utf8 locale doesn't exist

diff --git a/autotools/check-man b/autotools/check-man
--- a/autotools/check-man
+++ b/autotools/check-man
@@ -20,6 +20,11 @@
 
 set -e
 
+if ! locale -a | grep en_US.utf8 >/dev/null; then
+  echo "Error: Locale en_US.utf8 not found."
+  exit 1
+fi
+
 ! LANG=en_US.UTF-8 MANWIDTH=80 \
   man --warnings --encoding=utf8 --local-file "$1" 2>&1 >/dev/null | \
   grep -v -e "cannot adjust line" -e "can't break line" | \
